site_name: Umicom Studio IDE — Developer Docs
site_description: Official documentation for Umicom Studio IDE — setup, guides, API reference.
site_author: Umicom Foundation
repo_url: https://github.com/umicom-foundation/umicom-studio
repo_name: umicom-studio
theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - toc:
      permalink: "#"
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.keys
  - pymdownx.arithmatex:
      generic: true
plugins:
  - search
nav:
  - Home: index.md
  - Guide:
      - Getting started: guide/getting-started.md
      - Debugging tips: guide/debugging.md
      - Welcome new developers: guide/welcome-new-devs.md
  - How-to:
      - Build (Windows, MSYS2): how-to/build-windows-msys2.md
      - Build (Linux/macOS): how-to/build-unix.md
      - Run tests: how-to/run-tests.md
      - Format code: how-to/format-code.md
  - Explanations:
      - Architecture: explanations/architecture.md
      - Decisions (ADRs):
          - ADR-0001: explanations/decisions/ADR-0001-prefer-meson.md
  - Reference:
      - CLI options: reference/cli.md
      - Settings (config): reference/config.md
      - C API (Doxygen HTML): reference/api/index.html
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/umicom-foundation
