/*-----------------------------------------------------------------------------
 * Umicom Framework
 * File: include/umicom/document/capabilities.h
 *
 * PURPOSE:
 *   Aggregate the complete Framework-owned document capability inventory.
 *
 * Created by: Sammy Hegab
 * Organisation: Umicom Foundation
 * Licence: MIT
 *---------------------------------------------------------------------------*/
#ifndef UMICOM_DOCUMENT_CAPABILITIES_H
#define UMICOM_DOCUMENT_CAPABILITIES_H

#include "umicom/document/capability.h"
#include "umicom/document/capabilities/untitled_document.h"
#include "umicom/document/capabilities/open_document.h"
#include "umicom/document/capabilities/close_document.h"
#include "umicom/document/capabilities/reopen_document.h"
#include "umicom/document/capabilities/clone_document.h"
#include "umicom/document/capabilities/read_only_document.h"
#include "umicom/document/capabilities/large_document.h"
#include "umicom/document/capabilities/virtual_document.h"
#include "umicom/document/capabilities/resource_uri.h"
#include "umicom/document/capabilities/native_path.h"
#include "umicom/document/capabilities/path_canonicalization.h"
#include "umicom/document/capabilities/content_fingerprint.h"
#include "umicom/document/capabilities/file_stat.h"
#include "umicom/document/capabilities/display_name.h"
#include "umicom/document/capabilities/language_identity.h"
#include "umicom/document/capabilities/mime_identity.h"
#include "umicom/document/capabilities/local_file_provider.h"
#include "umicom/document/capabilities/memory_provider.h"
#include "umicom/document/capabilities/remote_provider.h"
#include "umicom/document/capabilities/archive_provider.h"
#include "umicom/document/capabilities/ssh_provider.h"
#include "umicom/document/capabilities/webdav_provider.h"
#include "umicom/document/capabilities/cloud_provider.h"
#include "umicom/document/capabilities/custom_provider.h"
#include "umicom/document/capabilities/utf8_encoding.h"
#include "umicom/document/capabilities/utf8_bom_encoding.h"
#include "umicom/document/capabilities/utf16le_encoding.h"
#include "umicom/document/capabilities/utf16be_encoding.h"
#include "umicom/document/capabilities/encoding_validation.h"
#include "umicom/document/capabilities/encoding_detection.h"
#include "umicom/document/capabilities/encoding_conversion.h"
#include "umicom/document/capabilities/bom_policy.h"
#include "umicom/document/capabilities/atomic_save.h"
#include "umicom/document/capabilities/save_as.h"
#include "umicom/document/capabilities/save_participant.h"
#include "umicom/document/capabilities/backup_copy.h"
#include "umicom/document/capabilities/permission_preservation.h"
#include "umicom/document/capabilities/line_ending_policy.h"
#include "umicom/document/capabilities/final_newline_policy.h"
#include "umicom/document/capabilities/trailing_whitespace_policy.h"
#include "umicom/document/capabilities/autosave.h"
#include "umicom/document/capabilities/recovery_journal.h"
#include "umicom/document/capabilities/hot_exit.h"
#include "umicom/document/capabilities/crash_recovery.h"
#include "umicom/document/capabilities/backup_rotation.h"
#include "umicom/document/capabilities/orphan_cleanup.h"
#include "umicom/document/capabilities/session_restore.h"
#include "umicom/document/capabilities/document_snapshot.h"
#include "umicom/document/capabilities/external_change_detection.h"
#include "umicom/document/capabilities/dirty_conflict.h"
#include "umicom/document/capabilities/three_way_conflict.h"
#include "umicom/document/capabilities/overwrite_resolution.h"
#include "umicom/document/capabilities/reload_resolution.h"
#include "umicom/document/capabilities/compare_resolution.h"
#include "umicom/document/capabilities/file_lock.h"
#include "umicom/document/capabilities/merge_resolution.h"
#include "umicom/document/capabilities/new_command.h"
#include "umicom/document/capabilities/open_command.h"
#include "umicom/document/capabilities/save_command.h"
#include "umicom/document/capabilities/save_as_command.h"
#include "umicom/document/capabilities/close_command.h"
#include "umicom/document/capabilities/close_all_command.h"
#include "umicom/document/capabilities/revert_command.h"
#include "umicom/document/capabilities/rename_command.h"
#include "umicom/document/capabilities/find_command.h"
#include "umicom/document/capabilities/replace_command.h"
#include "umicom/document/capabilities/go_to_line_command.h"
#include "umicom/document/capabilities/go_to_offset_command.h"
#include "umicom/document/capabilities/next_match_command.h"
#include "umicom/document/capabilities/previous_match_command.h"
#include "umicom/document/capabilities/recent_documents.h"
#include "umicom/document/capabilities/document_history.h"
#include "umicom/document/capabilities/workspace_trust.h"
#include "umicom/document/capabilities/symlink_policy.h"
#include "umicom/document/capabilities/path_traversal_policy.h"
#include "umicom/document/capabilities/file_size_limit.h"
#include "umicom/document/capabilities/binary_file_policy.h"
#include "umicom/document/capabilities/write_permission_policy.h"
#include "umicom/document/capabilities/document_audit.h"
#include "umicom/document/capabilities/sensitive_content_redaction.h"
#include "umicom/document/capabilities/memory_mapping.h"
#include "umicom/document/capabilities/streaming_loader.h"
#include "umicom/document/capabilities/incremental_fingerprint.h"
#include "umicom/document/capabilities/asynchronous_load.h"
#include "umicom/document/capabilities/asynchronous_save.h"
#include "umicom/document/capabilities/content_cache.h"
#include "umicom/document/capabilities/chunked_transport.h"
#include "umicom/document/capabilities/io_cancellation.h"
#include "umicom/document/capabilities/ui_document_model.h"
#include "umicom/document/capabilities/headless_document_host.h"
#include "umicom/document/capabilities/gtk4_document_host.h"
#include "umicom/document/capabilities/lsp_document_sync.h"
#include "umicom/document/capabilities/vcs_diff_bridge.h"
#include "umicom/document/capabilities/document_test_fixture.h"
#include "umicom/document/capabilities/provider_extension_point.h"
#include "umicom/document/capabilities/document_telemetry.h"

#endif /* UMICOM_DOCUMENT_CAPABILITIES_H */
