/*-----------------------------------------------------------------------------
 * Umicom Studio IDE
 * File: applications/studio/src/app/developer_workbench.c
 * PURPOSE: Implement ownership and lifecycle for Studio developer-platform centres.
 * Created by: Sammy Hegab
 * Organisation: Umicom Foundation
 * Licence: MIT
 *---------------------------------------------------------------------------*/
#include "umicom/studio/developer_workbench.h"
#include <stdlib.h>
#include <string.h>
struct UmiStudioDeveloperWorkbench{UmiStudioProjectCentre*projects;UmiStudioLanguageIntelligenceCentre*language;UmiStudioDebugCentre*debug;UmiStudioSourceControlCentre*source_control;UmiStudioTestExplorerCentre*tests;UmiUiWorkbenchServices*services;UmiStudioProblemsCentre*problems;UmiStudioOutputCentre*output;UmiStudioProgressCentre*progress;UmiStudioDeveloperSession*session;uint64_t revision;};
UmiStatus umi_studio_developer_workbench_create(UmiStudioDeveloperWorkbench**out){UmiStudioDeveloperWorkbench*p;UmiStatus s=UMI_STATUS_OK;if(out==NULL)return UMI_STATUS_INVALID_ARGUMENT;*out=NULL;p=calloc(1U,sizeof(*p));if(p==NULL)return UMI_STATUS_OUT_OF_MEMORY;p->revision=1U;if(s==UMI_STATUS_OK)s=umi_studio_project_centre_create(&p->projects);if(s==UMI_STATUS_OK)s=umi_studio_language_intelligence_centre_create(&p->language);if(s==UMI_STATUS_OK)s=umi_studio_debug_centre_create(&p->debug);if(s==UMI_STATUS_OK)s=umi_studio_source_control_centre_create(&p->source_control);if(s==UMI_STATUS_OK)s=umi_studio_test_explorer_centre_create(&p->tests);if(s==UMI_STATUS_OK)s=umi_ui_workbench_services_create(&p->services);if(s==UMI_STATUS_OK)s=umi_studio_problems_centre_create(p->services,&p->problems);if(s==UMI_STATUS_OK)s=umi_studio_output_centre_create(p->services,&p->output);if(s==UMI_STATUS_OK)s=umi_studio_progress_centre_create(p->services,&p->progress);if(s==UMI_STATUS_OK)s=umi_studio_developer_session_create(&p->session);if(s!=UMI_STATUS_OK){umi_studio_developer_workbench_destroy(p);return s;}*out=p;return UMI_STATUS_OK;}
void umi_studio_developer_workbench_destroy(UmiStudioDeveloperWorkbench*p){if(p==NULL)return;umi_studio_developer_session_destroy(p->session);umi_studio_progress_centre_destroy(p->progress);umi_studio_output_centre_destroy(p->output);umi_studio_problems_centre_destroy(p->problems);umi_ui_workbench_services_destroy(p->services);umi_studio_test_explorer_centre_destroy(p->tests);umi_studio_source_control_centre_destroy(p->source_control);umi_studio_debug_centre_destroy(p->debug);umi_studio_language_intelligence_centre_destroy(p->language);umi_studio_project_centre_destroy(p->projects);free(p);}
UmiStatus umi_studio_developer_workbench_snapshot(UmiStudioDeveloperWorkbench*p,UmiStudioDeveloperWorkbenchSnapshot*o){UmiStatus s;if(p==NULL||o==NULL)return UMI_STATUS_INVALID_ARGUMENT;memset(o,0,sizeof(*o));o->struct_size=(uint32_t)sizeof(*o);o->api_version=1U;o->revision=p->revision;o->available=1;s=umi_studio_project_centre_snapshot(p->projects,&o->projects);if(s!=UMI_STATUS_OK)return s;s=umi_studio_language_intelligence_centre_snapshot(p->language,&o->language);if(s!=UMI_STATUS_OK)return s;s=umi_studio_debug_centre_snapshot(p->debug,&o->debug);if(s!=UMI_STATUS_OK)return s;s=umi_studio_source_control_centre_snapshot(p->source_control,&o->source_control);if(s!=UMI_STATUS_OK)return s;s=umi_studio_test_explorer_centre_snapshot(p->tests,&o->tests);if(s!=UMI_STATUS_OK)return s;s=umi_studio_problems_centre_snapshot(p->problems,&o->problems);if(s!=UMI_STATUS_OK)return s;s=umi_studio_output_centre_snapshot(p->output,&o->output);if(s!=UMI_STATUS_OK)return s;s=umi_studio_progress_centre_snapshot(p->progress,&o->progress);if(s!=UMI_STATUS_OK)return s;s=umi_studio_developer_session_snapshot(p->session,&o->session);if(s!=UMI_STATUS_OK)return s;o->item_count=o->projects.service.item_count+o->language.service.item_count+o->debug.service.item_count+o->source_control.service.item_count+o->tests.service.total_count+o->problems.item_count+o->output.item_count+o->progress.item_count;return UMI_STATUS_OK;}
#define A(fn,type,field) type *fn(UmiStudioDeveloperWorkbench*p){return p!=NULL?p->field:NULL;}
A(umi_studio_developer_workbench_projects,UmiStudioProjectCentre,projects) A(umi_studio_developer_workbench_language,UmiStudioLanguageIntelligenceCentre,language) A(umi_studio_developer_workbench_debug,UmiStudioDebugCentre,debug) A(umi_studio_developer_workbench_source_control,UmiStudioSourceControlCentre,source_control) A(umi_studio_developer_workbench_tests,UmiStudioTestExplorerCentre,tests) A(umi_studio_developer_workbench_services,UmiUiWorkbenchServices,services) A(umi_studio_developer_workbench_session,UmiStudioDeveloperSession,session)
#undef A
