/*-----------------------------------------------------------------------------
 * Umicom Framework
 * File: include/umicom/editor/features.h
 *
 * PURPOSE:
 *   Aggregate every Framework-owned editor capability descriptor.
 *
 * Created by: Sammy Hegab
 * Organisation: Umicom Foundation
 * Licence: MIT
 *---------------------------------------------------------------------------*/
#ifndef UMICOM_EDITOR_FEATURES_H
#define UMICOM_EDITOR_FEATURES_H

#include "umicom/editor/feature.h"
#include "umicom/editor/features/text_buffer.h"
#include "umicom/editor/features/line_index.h"
#include "umicom/editor/features/text_position.h"
#include "umicom/editor/features/text_range.h"
#include "umicom/editor/features/text_snapshot.h"
#include "umicom/editor/features/document_identity.h"
#include "umicom/editor/features/document_metadata.h"
#include "umicom/editor/features/document_lifecycle.h"
#include "umicom/editor/features/document_loader.h"
#include "umicom/editor/features/document_saver.h"
#include "umicom/editor/features/document_autosave.h"
#include "umicom/editor/features/document_recovery.h"
#include "umicom/editor/features/document_encoding.h"
#include "umicom/editor/features/line_endings.h"
#include "umicom/editor/features/large_file_mode.h"
#include "umicom/editor/features/read_only_regions.h"
#include "umicom/editor/features/virtual_document.h"
#include "umicom/editor/features/document_conflict.h"
#include "umicom/editor/features/edit_operation.h"
#include "umicom/editor/features/edit_transaction.h"
#include "umicom/editor/features/edit_history.h"
#include "umicom/editor/features/multi_cursor.h"
#include "umicom/editor/features/multi_selection.h"
#include "umicom/editor/features/clipboard.h"
#include "umicom/editor/features/indentation.h"
#include "umicom/editor/features/comment_toggle.h"
#include "umicom/editor/features/bracket_matching.h"
#include "umicom/editor/features/auto_closing_pairs.h"
#include "umicom/editor/features/smart_indent.h"
#include "umicom/editor/features/word_operations.h"
#include "umicom/editor/features/line_operations.h"
#include "umicom/editor/features/case_transform.h"
#include "umicom/editor/features/sort_lines.h"
#include "umicom/editor/features/snippet.h"
#include "umicom/editor/features/format_on_type.h"
#include "umicom/editor/features/literal_search.h"
#include "umicom/editor/features/replace.h"
#include "umicom/editor/features/regex_search.h"
#include "umicom/editor/features/incremental_search.h"
#include "umicom/editor/features/go_to_line.h"
#include "umicom/editor/features/go_to_symbol.h"
#include "umicom/editor/features/go_to_definition.h"
#include "umicom/editor/features/go_to_reference.h"
#include "umicom/editor/features/navigation_history.h"
#include "umicom/editor/features/breadcrumb_navigation.h"
#include "umicom/editor/features/quick_open.h"
#include "umicom/editor/features/command_palette.h"
#include "umicom/editor/features/peek_view.h"
#include "umicom/editor/features/link_navigation.h"
#include "umicom/editor/features/editor_viewport.h"
#include "umicom/editor/features/editor_gutter.h"
#include "umicom/editor/features/line_numbers.h"
#include "umicom/editor/features/minimap.h"
#include "umicom/editor/features/overview_ruler.h"
#include "umicom/editor/features/word_wrap.h"
#include "umicom/editor/features/whitespace_rendering.h"
#include "umicom/editor/features/current_line.h"
#include "umicom/editor/features/indent_guides.h"
#include "umicom/editor/features/bracket_guides.h"
#include "umicom/editor/features/code_folding.h"
#include "umicom/editor/features/sticky_scroll.h"
#include "umicom/editor/features/editor_decoration.h"
#include "umicom/editor/features/semantic_highlighting.h"
#include "umicom/editor/features/syntax_highlighting.h"
#include "umicom/editor/features/inlay_hints.h"
#include "umicom/editor/features/code_lens.h"
#include "umicom/editor/features/editor_theme.h"
#include "umicom/editor/features/editor_tab.h"
#include "umicom/editor/features/editor_group.h"
#include "umicom/editor/features/editor_split.h"
#include "umicom/editor/features/preview_editor.h"
#include "umicom/editor/features/pinned_editor.h"
#include "umicom/editor/features/recent_editors.h"
#include "umicom/editor/features/workspace_trust.h"
#include "umicom/editor/features/workspace_state.h"
#include "umicom/editor/features/workspace_session.h"
#include "umicom/editor/features/file_watcher_sync.h"
#include "umicom/editor/features/file_compare.h"
#include "umicom/editor/features/three_way_merge.h"
#include "umicom/editor/features/diff_editor.h"
#include "umicom/editor/features/save_participants.h"
#include "umicom/editor/features/working_copy.h"
#include "umicom/editor/features/hot_exit.h"
#include "umicom/editor/features/language_binding.h"
#include "umicom/editor/features/completion_session.h"
#include "umicom/editor/features/hover.h"
#include "umicom/editor/features/signature_help.h"
#include "umicom/editor/features/diagnostic_collection.h"
#include "umicom/editor/features/quick_fix.h"
#include "umicom/editor/features/rename.h"
#include "umicom/editor/features/document_format.h"
#include "umicom/editor/features/document_symbols.h"
#include "umicom/editor/features/workspace_symbols.h"
#include "umicom/editor/features/semantic_tokens.h"
#include "umicom/editor/features/call_hierarchy.h"
#include "umicom/editor/features/type_hierarchy.h"
#include "umicom/editor/features/inline_completion.h"
#include "umicom/editor/features/linked_editing.h"
#include "umicom/editor/features/language_status.h"
#include "umicom/editor/features/problems_navigation.h"
#include "umicom/editor/features/source_control_decorations.h"
#include "umicom/editor/features/test_code_lens.h"
#include "umicom/editor/features/coverage_gutter.h"
#include "umicom/editor/features/breakpoint_gutter.h"
#include "umicom/editor/features/inline_debug_values.h"
#include "umicom/editor/features/task_diagnostics.h"
#include "umicom/editor/features/code_ownership.h"
#include "umicom/editor/features/performance_guard.h"
#include "umicom/editor/features/accessibility.h"
#include "umicom/editor/features/extension_points.h"
#include "umicom/editor/features/editor_commands.h"
#include "umicom/editor/features/editor_context_keys.h"
#include "umicom/editor/features/editor_keybindings.h"
#include "umicom/editor/features/remote_document.h"
#include "umicom/editor/features/collaborative_cursor.h"
#include "umicom/editor/features/collaborative_edit.h"
#include "umicom/editor/features/ai_edit_proposal.h"
#include "umicom/editor/features/audit_trail.h"
#include "umicom/editor/features/policy_gate.h"

#endif /* UMICOM_EDITOR_FEATURES_H */
