/*-----------------------------------------------------------------------------
 * Umicom Framework
 * File: include/umicom/umicom.h
 *
 * PURPOSE:
 *   Provide the aggregate public Framework include for applications that use
 *   the complete C23 foundation through the Umicom::Framework target.
 *
 * Created by: Sammy Hegab
 * Organisation: Umicom Foundation
 * Licence: MIT
 *---------------------------------------------------------------------------*/
#ifndef UMICOM_UMICOM_H
#define UMICOM_UMICOM_H

#include "umicom/base/version.h"
#include "umicom/base/status.h"
#include "umicom/base/result.h"
#include "umicom/base/memory.h"

#include "umicom/diagnostics/diagnostics.h"

#include "umicom/messaging/message.h"
#include "umicom/messaging/event_bus.h"
#include "umicom/messaging/command_bus.h"
#include "umicom/messaging/query_bus.h"
#include "umicom/messaging/journal.h"
#include "umicom/messaging/payload.h"
#include "umicom/messaging/schema.h"
#include "umicom/messaging/channel.h"
#include "umicom/messaging/subscription.h"
#include "umicom/messaging/dispatcher.h"
#include "umicom/messaging/reliability.h"
#include "umicom/messaging/replay.h"
#include "umicom/messaging/inbox.h"
#include "umicom/messaging/outbox.h"
#include "umicom/messaging/dead_letter.h"
#include "umicom/messaging/idempotency.h"
#include "umicom/messaging/delivery_lease.h"
#include "umicom/messaging/transport.h"
#include "umicom/messaging/router.h"
#include "umicom/messaging/filter.h"
#include "umicom/messaging/transformer.h"
#include "umicom/messaging/aggregator.h"
#include "umicom/messaging/resequencer.h"
#include "umicom/messaging/flow.h"
#include "umicom/messaging/workflow.h"
#include "umicom/messaging/saga.h"
#include "umicom/messaging/topic.h"
#include "umicom/messaging/metrics.h"

#include "umicom/data/data_server.h"
#include "umicom/data/store.h"
#include "umicom/data/repository.h"
#include "umicom/data/transaction.h"
#include "umicom/data/schema_version.h"
#include "umicom/data/migration.h"
#include "umicom/data/sqlite.h"
#include "umicom/data/statement.h"
#include "umicom/data/row.h"
#include "umicom/data/blob_store.h"
#include "umicom/data/cache.h"
#include "umicom/data/metadata.h"
#include "umicom/data/lineage.h"
#include "umicom/data/backup.h"
#include "umicom/data/integrity.h"
#include "umicom/data/message_store.h"
#include "umicom/data/journal_store.h"
#include "umicom/data/explorer.h"

#include "umicom/platform/config.h"
#include "umicom/platform/settings.h"
#include "umicom/platform/path.h"
#include "umicom/platform/filesystem.h"
#include "umicom/platform/directory.h"
#include "umicom/platform/cancellation.h"
#include "umicom/platform/atomic_file.h"
#include "umicom/platform/threading.h"
#include "umicom/platform/task.h"
#include "umicom/platform/task_queue.h"
#include "umicom/platform/document_store.h"
#include "umicom/platform/workspace_graph.h"
#include "umicom/platform/file_index.h"
#include "umicom/platform/search.h"
#include "umicom/platform/session_store.h"
#include "umicom/platform/recovery.h"
#include "umicom/platform/process.h"
#include "umicom/platform/process_supervisor.h"
#include "umicom/platform/watcher.h"
#include "umicom/platform/workspace.h"
#include "umicom/platform/document.h"
#include "umicom/platform/clock.h"
#include "umicom/platform/recent_items.h"
#include "umicom/platform/bookmarks.h"
#include "umicom/platform/resource_location.h"
#include "umicom/platform/workspace_history.h"
#include "umicom/platform/file_operation_queue.h"
#include "umicom/platform/resource_centre.h"

#include "umicom/security/policy.h"
#include "umicom/security/secrets.h"
#include "umicom/security/identity.h"
#include "umicom/security/permission.h"
#include "umicom/security/role.h"
#include "umicom/security/session.h"
#include "umicom/security/credential.h"
#include "umicom/security/token.h"
#include "umicom/security/secret_provider.h"
#include "umicom/security/redaction.h"
#include "umicom/security/workspace_trust.h"
#include "umicom/security/event.h"
#include "umicom/security/authorisation.h"
#include "umicom/security/context.h"
#include "umicom/security/security_admin.h"

#include "umicom/runtime/capability_registry.h"
#include "umicom/runtime/service_registry.h"
#include "umicom/runtime/command_registry.h"
#include "umicom/runtime/inventory.h"
#include "umicom/runtime/contract.h"
#include "umicom/runtime/health.h"
#include "umicom/runtime/capability_catalogue.h"
#include "umicom/runtime/application_manifest.h"
#include "umicom/runtime/suite.h"
#include "umicom/runtime/module.h"
#include "umicom/runtime/module_registry.h"
#include "umicom/runtime/master_controller.h"
#include "umicom/runtime/scheduler.h"

#include "umicom/integration/integration.h"

#include "umicom/resilience/backoff.h"
#include "umicom/resilience/retry.h"
#include "umicom/resilience/circuit_breaker.h"
#include "umicom/resilience/bulkhead.h"
#include "umicom/resilience/rate_limiter.h"
#include "umicom/resilience/restart_policy.h"
#include "umicom/resilience/deadline.h"
#include "umicom/resilience/fault.h"
#include "umicom/resilience/health_gate.h"
#include "umicom/resilience/supervisor.h"

#include "umicom/observability/observability_admin.h"

#include "umicom/ui/contracts.h"
#include "umicom/ui/headless.h"
#include "umicom/ui/gtk4.h"
#include "umicom/ui/components/components.h"
#include "umicom/ui/professional_workspace.h"

#include "umicom/editor/editor.h"
#include "umicom/document/document.h"
#include "umicom/project/project.h"
#include "umicom/language/language.h"
#include "umicom/debug/debug.h"
#include "umicom/source_control/source_control.h"
#include "umicom/test_platform/test_platform.h"
#include "umicom/developer/developer.h"

#include "umicom/build/types.h"
#include "umicom/build/profile.h"
#include "umicom/build/preset.h"
#include "umicom/build/diagnostic.h"
#include "umicom/build/parser.h"
#include "umicom/build/result.h"
#include "umicom/build/history.h"
#include "umicom/build/provider.h"
#include "umicom/build/cmake_provider.h"
#include "umicom/build/ninja_provider.h"
#include "umicom/build/ctest_provider.h"
#include "umicom/build/runner.h"
#include "umicom/build/graph.h"
#include "umicom/build/policy.h"
#include "umicom/build/plan.h"
#include "umicom/build/engine.h"
#include "umicom/build/artifact.h"
#include "umicom/diagnostic_ui/diagnostic_ui.h"

#include "umicom/testing/types.h"
#include "umicom/testing/case.h"
#include "umicom/testing/result.h"
#include "umicom/testing/suite.h"
#include "umicom/testing/registry.h"
#include "umicom/testing/discovery.h"
#include "umicom/testing/runner.h"
#include "umicom/testing/report.h"
#include "umicom/testing/ctest_adapter.h"

#include "umicom/terminal/terminal.h"
#include "umicom/terminal_ui/terminal_ui.h"

#include "umicom/protocol/types.h"
#include "umicom/protocol/framing.h"
#include "umicom/protocol/json.h"
#include "umicom/protocol/json_rpc.h"
#include "umicom/protocol/transport.h"
#include "umicom/protocol/client.h"
#include "umicom/protocol/lsp.h"
#include "umicom/protocol/lsp_extended.h"
#include "umicom/protocol/lsp_document.h"
#include "umicom/protocol/dap_extended.h"
#include "umicom/protocol/dap.h"
#include "umicom/protocol/dap_breakpoint.h"

#include "umicom/vcs/types.h"
#include "umicom/vcs/change.h"
#include "umicom/vcs/status.h"
#include "umicom/vcs/branch.h"
#include "umicom/vcs/branch_list.h"
#include "umicom/vcs/commit.h"
#include "umicom/vcs/history.h"
#include "umicom/vcs/diff.h"
#include "umicom/vcs/diff_document.h"
#include "umicom/vcs/remote.h"
#include "umicom/vcs/tag.h"
#include "umicom/vcs/conflict.h"
#include "umicom/vcs/operation_log.h"
#include "umicom/vcs/provider.h"
#include "umicom/vcs/repository.h"
#include "umicom/vcs/git_cli.h"
#include "umicom/vcs/workspace.h"
#include "umicom/vcs_ui/vcs_ui.h"

#include "umicom/declarative/declarative.h"
#include "umicom/designer/designer.h"

#include "umicom/web/types.h"
#include "umicom/web/header.h"
#include "umicom/web/request.h"
#include "umicom/web/response.h"
#include "umicom/web/url.h"
#include "umicom/web/query.h"
#include "umicom/web/parser.h"
#include "umicom/web/route.h"
#include "umicom/web/router.h"
#include "umicom/web/middleware.h"
#include "umicom/web/mime.h"
#include "umicom/web/static_files.h"
#include "umicom/web/json.h"
#include "umicom/web/rest.h"
#include "umicom/web/sse.h"
#include "umicom/web/websocket.h"
#include "umicom/web/session.h"
#include "umicom/web/origin.h"
#include "umicom/web/security.h"
#include "umicom/web/endpoint.h"
#include "umicom/web/metrics.h"
#include "umicom/web/server_config.h"
#include "umicom/web/server_state.h"
#include "umicom/web/listener.h"
#include "umicom/web/service.h"
#include "umicom/web/runtime.h"
#include "umicom/web/server.h"

#include "umicom/browser/types.h"
#include "umicom/browser/browser.h"
#include "umicom/browser/navigation.h"
#include "umicom/browser/bridge.h"
#include "umicom/browser/headless.h"
#include "umicom/browser/policy.h"

#include "umicom/chart/types.h"
#include "umicom/chart/candle.h"
#include "umicom/chart/series.h"
#include "umicom/chart/viewport.h"
#include "umicom/chart/model.h"
#include "umicom/chart/indicator.h"
#include "umicom/chart/snapshot.h"
#include "umicom/chart/json.h"

#include "umicom/frontend/types.h"
#include "umicom/frontend/page.h"
#include "umicom/frontend/route.h"
#include "umicom/frontend/asset.h"
#include "umicom/frontend/plan.h"
#include "umicom/frontend/renderer.h"
#include "umicom/frontend/generator.h"
#include "umicom/frontend/gtkjs.h"
#include "umicom/frontend/headless.h"

#include "umicom/ai/ai.h"
#include "umicom/ai_ui/ai_ui.h"
#include "umicom/knowledge/knowledge.h"
#include "umicom/knowledge_ui/knowledge_ui.h"
#include "umicom/helix/helix.h"
#include "umicom/delivery/delivery.h"

#include "umicom/abi/abi.h"
#include "umicom/sdk/sdk.h"
#include "umicom/product/product.h"
#include "umicom/distribution/distribution.h"
#include "umicom/distribution_ui/distribution_ui.h"
#include "umicom/codeguard/codeguard.h"

#include "umicom/runtime/capability_registry.h"
#include "umicom/runtime/service_registry.h"
#include "umicom/runtime/command_registry.h"
#include "umicom/runtime/health.h"
#include "umicom/runtime/capability_catalogue.h"
#include "umicom/runtime/application_manifest.h"
#include "umicom/runtime/suite.h"
#include "umicom/runtime/module.h"
#include "umicom/runtime/module_registry.h"
#include "umicom/runtime/master_controller.h"
#include "umicom/runtime/scheduler.h"

#include "umicom/integration/integration.h"

#include "umicom/toolchain/tool.h"
#include "umicom/toolchain/profile.h"
#include "umicom/toolchain/discovery.h"
#include "umicom/toolchain/environment.h"
#include "umicom/toolchain/dependency.h"
#include "umicom/toolchain/build.h"
#include "umicom/toolchain/capability.h"
#include "umicom/toolchain/catalogue.h"
#include "umicom/toolchain/sdk.h"
#include "umicom/toolchain/compilation_database.h"

/* Batch 58 unified compiler, polyglot build and Umicc integration surface. */
#include "umicom/compiler/compiler.h"

#include "umicom/resilience/backoff.h"
#include "umicom/resilience/retry.h"
#include "umicom/resilience/circuit_breaker.h"
#include "umicom/resilience/bulkhead.h"
#include "umicom/resilience/rate_limiter.h"
#include "umicom/resilience/restart_policy.h"
#include "umicom/resilience/deadline.h"
#include "umicom/resilience/fault.h"
#include "umicom/resilience/health_gate.h"
#include "umicom/resilience/supervisor.h"

#include "umicom/repository/repository.h"
#include "umicom/scaffold/scaffold.h"
#include "umicom/scaffold/repository.h"
#include "umicom/plugin/plugin.h"
#include "umicom/plugin/state.h"
#include "umicom/plugin/manifest.h"
#include "umicom/plugin/permission.h"
#include "umicom/plugin/contribution.h"
#include "umicom/plugin/registry.h"
#include "umicom/plugin/checksum.h"
#include "umicom/plugin/signature.h"
#include "umicom/plugin/compatibility.h"
#include "umicom/plugin/discovery.h"
#include "umicom/plugin/loader.h"
#include "umicom/plugin/lifecycle.h"
#include "umicom/plugin/host.h"
#include "umicom/plugin/plugin_sdk.h"
#include "umicom/plugin_ui/plugin_ui.h"
#include "umicom/declarative/declarative.h"
#include "umicom/designer/designer.h"
#include "umicom/web/types.h"
#include "umicom/web/server.h"
#include "umicom/browser/browser.h"
#include "umicom/chart/types.h"
#include "umicom/chart/model.h"
#include "umicom/chart/interaction.h"
#include "umicom/frontend/types.h"
#include "umicom/frontend/plan.h"
#include "umicom/frontend/application.h"
#include "umicom/frontend/platform.h"
#include "umicom/ai/ai.h"
#include "umicom/ai_ui/ai_ui.h"
#include "umicom/knowledge/knowledge.h"
#include "umicom/knowledge_ui/knowledge_ui.h"
#include "umicom/helix/helix.h"
#include "umicom/delivery/delivery.h"
#include "umicom/abi/abi.h"
#include "umicom/sdk/sdk.h"
#include "umicom/product/product.h"
#include "umicom/product/centre.h"
#include "umicom/distribution/distribution.h"
#include "umicom/distribution_ui/distribution_ui.h"
#include "umicom/codeguard/codeguard.h"
#include "umicom/toolchain/tool.h"
#include "umicom/toolchain/profile.h"
#include "umicom/toolchain/discovery.h"
#include "umicom/toolchain/environment.h"
#include "umicom/toolchain/dependency.h"
#include "umicom/toolchain/build.h"

#endif
