/*-----------------------------------------------------------------------------
 * Umicom AuthorEngine AI (uaengine)
 * File: include/ueng/version.h
 * Purpose: Version string
 *  Created by: Umicom Foundation (https://umicom.foundation/)
 * Author: Sammy Hegab
 * License: MIT
 * Date: 23-09-2025
 *
 *---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------
 * Module notes (added, non-destructive):
 * MODULE OVERVIEW
 * ----------------
 * Purpose: Build-time version and metadata surface.
 * How it works:
 *   - Values are generated by CMake or defined here for local builds.
 *   - Used by '--version' output and HTML footers.
 *---------------------------------------------------------------------------*/

#ifndef UENG_VERSION_H
#define UENG_VERSION_H

/* Public version string used by --version and in build banners. */
#define UENG_VERSION_STRING "uaengine v0.1.4"

/* Alias to keep callsites simple (some code uses UENG_VERSION_STR). */
#define UENG_VERSION_STR UENG_VERSION_STRING
#endif
/*------------------------------ Implementation ------------------------------*/
