# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 3.0.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "3.0.0")
   message(FATAL_ERROR "CMake >= 3.0.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 3.0.0...4.2)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS Umicom::base Umicom::diagnostics Umicom::messaging Umicom::data Umicom::platform Umicom::security Umicom::runtime Umicom::integration Umicom::resilience Umicom::observability Umicom::toolchain Umicom::compiler Umicom::repository Umicom::plugin Umicom::plugin_ui Umicom::scaffold Umicom::ui Umicom::ui_components Umicom::ui_headless Umicom::build Umicom::build_ui Umicom::diagnostic_ui Umicom::testing Umicom::terminal Umicom::terminal_ui Umicom::protocol Umicom::editor Umicom::document Umicom::vcs Umicom::vcs_ui Umicom::declarative Umicom::designer Umicom::web Umicom::browser Umicom::chart Umicom::frontend Umicom::ai Umicom::ai_ui Umicom::helix Umicom::delivery Umicom::abi Umicom::sdk Umicom::product Umicom::distribution Umicom::distribution_ui Umicom::finance Umicom::trading Umicom::trading_ui Umicom::codeguard Umicom::project Umicom::language Umicom::debug Umicom::source_control Umicom::test_platform Umicom::test_ui Umicom::developer Umicom::Framework Umicom::ui_gtk4)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target Umicom::base
add_library(Umicom::base STATIC IMPORTED)

set_target_properties(Umicom::base PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

# Create imported target Umicom::diagnostics
add_library(Umicom::diagnostics STATIC IMPORTED)

set_target_properties(Umicom::diagnostics PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Umicom::base"
)

# Create imported target Umicom::messaging
add_library(Umicom::messaging STATIC IMPORTED)

set_target_properties(Umicom::messaging PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Umicom::base"
)

# Create imported target Umicom::data
add_library(Umicom::data STATIC IMPORTED)

set_target_properties(Umicom::data PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "UMICOM_HAS_SQLITE=1"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Umicom::base;Umicom::messaging;SQLite3::SQLite3"
)

# Create imported target Umicom::platform
add_library(Umicom::platform STATIC IMPORTED)

set_target_properties(Umicom::platform PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Umicom::base;Umicom::finance;Umicom::trading;Umicom::diagnostics;Threads::Threads"
)

# Create imported target Umicom::security
add_library(Umicom::security STATIC IMPORTED)

set_target_properties(Umicom::security PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Umicom::base;Umicom::platform"
)

# Create imported target Umicom::runtime
add_library(Umicom::runtime STATIC IMPORTED)

set_target_properties(Umicom::runtime PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Umicom::base;Umicom::diagnostics;Umicom::messaging;Umicom::data;Umicom::platform;Umicom::security"
)

# Create imported target Umicom::integration
add_library(Umicom::integration STATIC IMPORTED)

set_target_properties(Umicom::integration PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Umicom::base;Umicom::messaging;Umicom::platform;Umicom::security;Umicom::runtime"
)

# Create imported target Umicom::resilience
add_library(Umicom::resilience STATIC IMPORTED)

set_target_properties(Umicom::resilience PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Umicom::base;Umicom::platform;Umicom::runtime"
)

# Create imported target Umicom::observability
add_library(Umicom::observability STATIC IMPORTED)

set_target_properties(Umicom::observability PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Umicom::base;Umicom::diagnostics;Umicom::runtime;Umicom::resilience"
)

# Create imported target Umicom::toolchain
add_library(Umicom::toolchain STATIC IMPORTED)

set_target_properties(Umicom::toolchain PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Umicom::base;Umicom::diagnostics;Umicom::platform"
)

# Create imported target Umicom::compiler
add_library(Umicom::compiler STATIC IMPORTED)

set_target_properties(Umicom::compiler PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Umicom::base;Umicom::toolchain"
)

# Create imported target Umicom::repository
add_library(Umicom::repository STATIC IMPORTED)

set_target_properties(Umicom::repository PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Umicom::base;Umicom::platform;Umicom::toolchain"
)

# Create imported target Umicom::plugin
add_library(Umicom::plugin STATIC IMPORTED)

set_target_properties(Umicom::plugin PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Umicom::base;Umicom::runtime;Umicom::security;Umicom::resilience"
)

# Create imported target Umicom::plugin_ui
add_library(Umicom::plugin_ui STATIC IMPORTED)

set_target_properties(Umicom::plugin_ui PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Umicom::plugin;Umicom::ui"
)

# Create imported target Umicom::scaffold
add_library(Umicom::scaffold STATIC IMPORTED)

set_target_properties(Umicom::scaffold PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Umicom::base;Umicom::platform;Umicom::runtime;Umicom::toolchain;Umicom::repository"
)

# Create imported target Umicom::ui
add_library(Umicom::ui STATIC IMPORTED)

set_target_properties(Umicom::ui PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Umicom::base;Umicom::platform;Umicom::runtime"
)

# Create imported target Umicom::ui_components
add_library(Umicom::ui_components STATIC IMPORTED)

set_target_properties(Umicom::ui_components PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Umicom::ui"
)

# Create imported target Umicom::ui_headless
add_library(Umicom::ui_headless STATIC IMPORTED)

set_target_properties(Umicom::ui_headless PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Umicom::ui;Umicom::ui_components"
)

# Create imported target Umicom::build
add_library(Umicom::build STATIC IMPORTED)

set_target_properties(Umicom::build PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Umicom::base;Umicom::diagnostics;Umicom::platform"
)

# Create imported target Umicom::build_ui
add_library(Umicom::build_ui STATIC IMPORTED)

set_target_properties(Umicom::build_ui PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Umicom::build;Umicom::ui"
)

# Create imported target Umicom::diagnostic_ui
add_library(Umicom::diagnostic_ui STATIC IMPORTED)

set_target_properties(Umicom::diagnostic_ui PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Umicom::diagnostics;Umicom::ui;Umicom::build"
)

# Create imported target Umicom::testing
add_library(Umicom::testing STATIC IMPORTED)

set_target_properties(Umicom::testing PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Umicom::base;Umicom::platform"
)

# Create imported target Umicom::terminal
add_library(Umicom::terminal STATIC IMPORTED)

set_target_properties(Umicom::terminal PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Umicom::base;Umicom::platform"
)

# Create imported target Umicom::terminal_ui
add_library(Umicom::terminal_ui STATIC IMPORTED)

set_target_properties(Umicom::terminal_ui PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Umicom::build;Umicom::terminal;Umicom::diagnostics;Umicom::ui"
)

# Create imported target Umicom::protocol
add_library(Umicom::protocol STATIC IMPORTED)

set_target_properties(Umicom::protocol PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Umicom::base;Umicom::platform"
)

# Create imported target Umicom::editor
add_library(Umicom::editor STATIC IMPORTED)

set_target_properties(Umicom::editor PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Umicom::base"
)

# Create imported target Umicom::document
add_library(Umicom::document STATIC IMPORTED)

set_target_properties(Umicom::document PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Umicom::base;Umicom::platform;Umicom::runtime;Umicom::ui;Umicom::editor"
)

# Create imported target Umicom::vcs
add_library(Umicom::vcs STATIC IMPORTED)

set_target_properties(Umicom::vcs PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Umicom::base;Umicom::platform"
)

# Create imported target Umicom::vcs_ui
add_library(Umicom::vcs_ui STATIC IMPORTED)

set_target_properties(Umicom::vcs_ui PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Umicom::vcs;Umicom::ui"
)

# Create imported target Umicom::declarative
add_library(Umicom::declarative STATIC IMPORTED)

set_target_properties(Umicom::declarative PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Umicom::base"
)

# Create imported target Umicom::designer
add_library(Umicom::designer STATIC IMPORTED)

set_target_properties(Umicom::designer PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Umicom::declarative;Umicom::runtime"
)

# Create imported target Umicom::web
add_library(Umicom::web STATIC IMPORTED)

set_target_properties(Umicom::web PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Umicom::base;Umicom::platform;\$<LINK_ONLY:ws2_32>"
)

# Create imported target Umicom::browser
add_library(Umicom::browser STATIC IMPORTED)

set_target_properties(Umicom::browser PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Umicom::base;Umicom::web"
)

# Create imported target Umicom::chart
add_library(Umicom::chart STATIC IMPORTED)

set_target_properties(Umicom::chart PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Umicom::base;Umicom::web"
)

# Create imported target Umicom::frontend
add_library(Umicom::frontend STATIC IMPORTED)

set_target_properties(Umicom::frontend PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Umicom::base;Umicom::web"
)

# Create imported target Umicom::ai
add_library(Umicom::ai STATIC IMPORTED)

set_target_properties(Umicom::ai PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Umicom::base;Umicom::platform;Umicom::security;Umicom::diagnostics"
)

# Create imported target Umicom::ai_ui
add_library(Umicom::ai_ui STATIC IMPORTED)

set_target_properties(Umicom::ai_ui PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Umicom::ai;Umicom::ui"
)

# Create imported target Umicom::helix
add_library(Umicom::helix STATIC IMPORTED)

set_target_properties(Umicom::helix PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Umicom::base;Umicom::ai;Umicom::runtime;Umicom::security;Umicom::ui"
)

# Create imported target Umicom::delivery
add_library(Umicom::delivery STATIC IMPORTED)

set_target_properties(Umicom::delivery PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Umicom::base;Umicom::platform;Umicom::build;Umicom::testing;Umicom::vcs"
)

# Create imported target Umicom::abi
add_library(Umicom::abi STATIC IMPORTED)

set_target_properties(Umicom::abi PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Umicom::base"
)

# Create imported target Umicom::sdk
add_library(Umicom::sdk STATIC IMPORTED)

set_target_properties(Umicom::sdk PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Umicom::base;Umicom::platform;Umicom::abi"
)

# Create imported target Umicom::product
add_library(Umicom::product STATIC IMPORTED)

set_target_properties(Umicom::product PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Umicom::base;Umicom::runtime"
)

# Create imported target Umicom::distribution
add_library(Umicom::distribution STATIC IMPORTED)

set_target_properties(Umicom::distribution PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Umicom::base;Umicom::delivery;Umicom::product"
)

# Create imported target Umicom::distribution_ui
add_library(Umicom::distribution_ui STATIC IMPORTED)

set_target_properties(Umicom::distribution_ui PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Umicom::distribution;Umicom::ui"
)

# Create imported target Umicom::finance
add_library(Umicom::finance STATIC IMPORTED)

set_target_properties(Umicom::finance PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Umicom::base"
)

# Create imported target Umicom::trading
add_library(Umicom::trading STATIC IMPORTED)

set_target_properties(Umicom::trading PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Umicom::base;Umicom::chart;Umicom::finance"
)

# Create imported target Umicom::trading_ui
add_library(Umicom::trading_ui STATIC IMPORTED)

set_target_properties(Umicom::trading_ui PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Umicom::trading;Umicom::ui"
)

# Create imported target Umicom::codeguard
add_library(Umicom::codeguard STATIC IMPORTED)

set_target_properties(Umicom::codeguard PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Umicom::base;Umicom::platform"
)

# Create imported target Umicom::project
add_library(Umicom::project STATIC IMPORTED)

set_target_properties(Umicom::project PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Umicom::base;Umicom::platform;Umicom::build"
)

# Create imported target Umicom::language
add_library(Umicom::language STATIC IMPORTED)

set_target_properties(Umicom::language PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Umicom::base;Umicom::platform;Umicom::protocol;Umicom::toolchain"
)

# Create imported target Umicom::debug
add_library(Umicom::debug STATIC IMPORTED)

set_target_properties(Umicom::debug PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Umicom::base;Umicom::platform;Umicom::protocol"
)

# Create imported target Umicom::source_control
add_library(Umicom::source_control STATIC IMPORTED)

set_target_properties(Umicom::source_control PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Umicom::base;Umicom::platform;Umicom::vcs"
)

# Create imported target Umicom::test_platform
add_library(Umicom::test_platform STATIC IMPORTED)

set_target_properties(Umicom::test_platform PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Umicom::base;Umicom::platform;Umicom::testing"
)

# Create imported target Umicom::test_ui
add_library(Umicom::test_ui STATIC IMPORTED)

set_target_properties(Umicom::test_ui PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Umicom::test_platform;Umicom::ui"
)

# Create imported target Umicom::developer
add_library(Umicom::developer STATIC IMPORTED)

set_target_properties(Umicom::developer PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Umicom::base;Umicom::platform;Umicom::ui;Umicom::project;Umicom::language;Umicom::debug;Umicom::source_control;Umicom::test_platform"
)

# Create imported target Umicom::Framework
add_library(Umicom::Framework INTERFACE IMPORTED)

set_target_properties(Umicom::Framework PROPERTIES
  INTERFACE_LINK_LIBRARIES "Umicom::base;Umicom::diagnostics;Umicom::messaging;Umicom::data;Umicom::platform;Umicom::security;Umicom::runtime;Umicom::integration;Umicom::resilience;Umicom::observability;Umicom::toolchain;Umicom::compiler;Umicom::repository;Umicom::plugin;Umicom::plugin_ui;Umicom::scaffold;Umicom::ui;Umicom::ui_components;Umicom::ui_headless;Umicom::build;Umicom::build_ui;Umicom::diagnostic_ui;Umicom::testing;Umicom::terminal;Umicom::terminal_ui;Umicom::protocol;Umicom::editor;Umicom::document;Umicom::vcs;Umicom::vcs_ui;Umicom::declarative;Umicom::designer;Umicom::web;Umicom::browser;Umicom::chart;Umicom::frontend;Umicom::ai;Umicom::ai_ui;Umicom::helix;Umicom::delivery;Umicom::abi;Umicom::sdk;Umicom::product;Umicom::distribution;Umicom::distribution_ui;Umicom::codeguard;Umicom::project;Umicom::language;Umicom::debug;Umicom::source_control;Umicom::test_platform;Umicom::test_ui;Umicom::developer;Umicom::finance;Umicom::trading;Umicom::trading_ui"
)

# Create imported target Umicom::ui_gtk4
add_library(Umicom::ui_gtk4 STATIC IMPORTED)

set_target_properties(Umicom::ui_gtk4 PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Umicom::ui;Umicom::ui_components;PkgConfig::UMICOM_FRAMEWORK_GTK4;\$<LINK_ONLY:PkgConfig::UMICOM_FRAMEWORK_SOURCEVIEW5>;Umicom::diagnostic_ui;Umicom::terminal_ui;Umicom::vcs_ui"
)

# Load information for each installed configuration.
file(GLOB _cmake_config_files "${CMAKE_CURRENT_LIST_DIR}/UmicomFrameworkTargets-*.cmake")
foreach(_cmake_config_file IN LISTS _cmake_config_files)
  include("${_cmake_config_file}")
endforeach()
unset(_cmake_config_file)
unset(_cmake_config_files)

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(_cmake_target IN LISTS _cmake_import_check_targets)
  if(CMAKE_VERSION VERSION_LESS "3.28"
      OR NOT DEFINED _cmake_import_check_xcframework_for_${_cmake_target}
      OR NOT IS_DIRECTORY "${_cmake_import_check_xcframework_for_${_cmake_target}}")
    foreach(_cmake_file IN LISTS "_cmake_import_check_files_for_${_cmake_target}")
      if(NOT EXISTS "${_cmake_file}")
        message(FATAL_ERROR "The imported target \"${_cmake_target}\" references the file
   \"${_cmake_file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
      endif()
    endforeach()
  endif()
  unset(_cmake_file)
  unset("_cmake_import_check_files_for_${_cmake_target}")
endforeach()
unset(_cmake_target)
unset(_cmake_import_check_targets)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
