name: build
on: [push, pull_request]
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: deps
        run: sudo apt update && sudo apt install -y libgtk-4-dev libjson-glib-dev meson ninja-build
      - name: build
        run: meson setup build && meson compile -C build
